project:
  type: website
  output-dir: docs
  resources:
    - "*.pdf"


website:
  title: "Bohan Zhang"
  page-footer: "Copyright 2023, Bohan Zhang"
  favicon: profile.jpg

  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Publications
        href: publications
      - software.qmd
      - text: Talks
        href: talks
      - about.qmd
      
    tools:
      - icon: github
        href: https://github.com/angelpone
      - icon: twitter
        href: https://twitter.com/zhangbhangel

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    template-partials: 
      - title-metadata.html
    author-title: AUTHORS



