project:
  type: website
  pre-render:
    - cv/cv.sh
  output-dir: docs
  resources:
    - "*.pdf"
    - CNAME
    - "activity/*.json"

website:
  title: "Bohan Zhang"
  page-footer: "Copyright 2023-2025, Bohan Zhang"
  favicon: profile.jpg

  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Publications
        href: publications
      - software.qmd
      - text: Talks
        href: talks
      - text: CV
        href: cv/cv.pdf
      - about.qmd

    tools:
      - icon: github
        href: https://github.com/angelpone
      - icon: twitter
        href: https://twitter.com/zhangbhangel

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    author-title: AUTHORS
